# Generated by Django 6.0.6 on 2026-07-03 05:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_alter_imagingorder_clinical_indication_and_more'),
        ('patients', '0003_patient_allergies_patient_chronic_conditions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('findings', models.TextField(blank=True, help_text='Findings from imaging')),
                ('impressions', models.TextField(blank=True, help_text='Impressions')),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='imaging_results/')),
                ('technician_notes', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes about the results")),
                ('clarification_request', models.TextField(blank=True, help_text="Technician's clarification request")),
                ('clarification_response', models.TextField(blank=True, help_text="Doctor's response")),
                ('clarification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('clarification_responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('clarification_needed', 'Clarification Needed'), ('clarification_responded', 'Clarification Responded')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('imaging_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='doctors.imagingorder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='patients.patient')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_imaging_results', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_results', to='patients.patientvisit')),
            ],
            options={
                'db_table': 'imaging_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('results', models.TextField(blank=True, help_text='Test results')),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('technician_notes', models.TextField(blank=True)),
                ('doctor_notes', models.TextField(blank=True, help_text="Doctor's notes about the results")),
                ('clarification_request', models.TextField(blank=True, help_text="Lab technician's clarification request")),
                ('clarification_response', models.TextField(blank=True, help_text="Doctor's response")),
                ('clarification_requested_at', models.DateTimeField(blank=True, null=True)),
                ('clarification_responded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('clarification_needed', 'Clarification Needed'), ('clarification_responded', 'Clarification Responded')], default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('lab_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='doctors.laborder')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patient')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lab_results', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_results', to='patients.patientvisit')),
            ],
            options={
                'db_table': 'lab_results',
                'ordering': ['-created_at'],
            },
        ),
    ]
