# Generated by Django 6.0.6 on 2026-07-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='triagerecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='needs_nursing_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='nursing_care_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='nursing_care_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='nursing_instructions',
            field=models.TextField(blank=True, help_text='Instructions from doctor for nursing care'),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='nursing_notes',
            field=models.TextField(blank=True, help_text='Notes from nurse'),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='sent_to_doctor_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='triagerecord',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('sent_to_doctor', 'Sent to Doctor'), ('nursing_care', 'Nursing Care'), ('completed_care', 'Completed Care')], default='waiting', max_length=20),
        ),
        migrations.AlterModelTable(
            name='triagerecord',
            table='triage_records',
        ),
    ]
