# Generated by Django 6.0.6 on 2026-07-01 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='category',
            field=models.CharField(choices=[('medicine', 'Medicine'), ('supply', 'Medical Supply'), ('equipment', 'Equipment')], default='medicine', max_length=20),
        ),
        migrations.AddField(
            model_name='medicine',
            name='storage_location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='medicine',
            name='supplier',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
