# Generated by Django 6.0.6 on 2026-07-03 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0003_alter_imagingorder_clinical_indication_and_more'),
        ('patients', '0003_patient_allergies_patient_chronic_conditions_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administered_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('administered', 'Administered'), ('refused', 'Refused'), ('held', 'Held'), ('missed', 'Missed')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administered_medications', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='patients.patient')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='doctors.prescription')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='patients.patientvisit')),
            ],
            options={
                'db_table': 'medication_administrations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NurseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('is_feedback', models.BooleanField(default=False, help_text='Is this feedback to the doctor?')),
                ('feedback_type', models.CharField(blank=True, help_text='Type of feedback (e.g., medication reaction, vitals change, etc.)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nurse_notes', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_notes', to='patients.patientvisit')),
            ],
            options={
                'db_table': 'nurse_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_type', models.CharField(choices=[('vitals', 'Vitals Check'), ('behavior', 'Behavior Change'), ('symptom', 'New Symptom'), ('improvement', 'Improvement'), ('deterioration', 'Deterioration'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField()),
                ('is_urgent', models.BooleanField(default=False, help_text='Is this observation urgent?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.patient')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='patients.patientvisit')),
            ],
            options={
                'db_table': 'patient_observations',
                'ordering': ['-created_at'],
            },
        ),
    ]
