# Generated by Django 6.0.6 on 2026-06-30 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientvisit',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date']},
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='imaging_ordered',
            field=models.BooleanField(default=False, help_text='True if imaging was ordered'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='is_priority_return',
            field=models.BooleanField(default=False, help_text='True if returning from lab/imaging - goes to front of queue'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='lab_ordered',
            field=models.BooleanField(default=False, help_text='True if lab tests were ordered'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='queue_position',
            field=models.IntegerField(default=0, help_text="Position in doctor's queue"),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='return_from_imaging',
            field=models.BooleanField(default=False, help_text='True if returning from imaging'),
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='return_from_lab',
            field=models.BooleanField(default=False, help_text='True if returning from lab'),
        ),
        migrations.AlterModelTable(
            name='patientvisit',
            table='patient_visits',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payments',
        ),
    ]
