# Generated by Django 6.0.6 on 2026-07-01 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patientvisit_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='allergies',
            field=models.TextField(blank=True, help_text='List all allergies'),
        ),
        migrations.AddField(
            model_name='patient',
            name='chronic_conditions',
            field=models.TextField(blank=True, help_text='Chronic conditions (diabetes, hypertension, etc.)'),
        ),
        migrations.AddField(
            model_name='patient',
            name='current_medications',
            field=models.TextField(blank=True, help_text='Current medications'),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_medical_history',
            field=models.TextField(blank=True, help_text='Family medical history'),
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history_notes',
            field=models.TextField(blank=True, help_text='Additional medical history notes'),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_surgeries',
            field=models.TextField(blank=True, help_text='Previous surgeries and procedures'),
        ),
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('admitted', 'Admitted'), ('discharged', 'Discharged'), ('referred', 'Referred'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='imaging_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='is_priority_return',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='lab_ordered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='queue_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='return_from_imaging',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patientvisit',
            name='return_from_lab',
            field=models.BooleanField(default=False),
        ),
    ]
