# Generated by Django 6.0.6 on 2026-06-30 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.TextField(help_text="Patient's reported symptoms")),
                ('symptom_duration', models.CharField(blank=True, help_text='How long symptoms have been present', max_length=100)),
                ('symptom_severity', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, help_text='1 = Mild, 10 = Severe')),
                ('clinical_notes', models.TextField(blank=True, help_text="Doctor's clinical observations")),
                ('diagnosis', models.TextField()),
                ('diagnosis_code', models.CharField(blank=True, help_text='ICD-10 code if available', max_length=50)),
                ('differential_diagnosis', models.TextField(blank=True, help_text='Other possible diagnoses')),
                ('ml_suggestion', models.TextField(blank=True, help_text='ML suggested diagnosis')),
                ('ml_confidence', models.DecimalField(blank=True, decimal_places=2, help_text='ML confidence score (0-100%)', max_digits=5, null=True)),
                ('ml_medication_suggestions', models.TextField(blank=True, help_text='ML suggested medications')),
                ('ml_used', models.BooleanField(default=False, help_text='Whether ML was used for this diagnosis')),
                ('treatment_plan', models.TextField()),
                ('referred_to_lab', models.BooleanField(default=False)),
                ('referred_to_imaging', models.BooleanField(default=False)),
                ('referred_to_specialist', models.BooleanField(default=False)),
                ('referral_notes', models.TextField(blank=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('follow_up_instructions', models.TextField(blank=True)),
                ('is_admitted', models.BooleanField(default=False)),
                ('admission_date', models.DateTimeField(blank=True, null=True)),
                ('discharge_date', models.DateTimeField(blank=True, null=True)),
                ('days_of_stay', models.IntegerField(default=0, help_text='Calculated automatically')),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patient')),
                ('triage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='triage.triagerecord')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientvisit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=200)),
                ('test_type', models.CharField(max_length=50)),
                ('clinical_notes', models.TextField(blank=True, help_text='What to look for')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('results', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='patients.patient')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_lab_tests', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_orders', to='doctors.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ImagingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imaging_type', models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('pet', 'PET Scan'), ('ecg', 'ECG/EKG'), ('other', 'Other')], max_length=20)),
                ('body_part', models.CharField(max_length=100)),
                ('clinical_indication', models.TextField(help_text='Why this imaging is needed')),
                ('priority', models.CharField(choices=[('routine', 'Routine'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='routine', max_length=20)),
                ('findings', models.TextField(blank=True)),
                ('impressions', models.TextField(blank=True)),
                ('result_date', models.DateTimeField(blank=True, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='imaging_results/')),
                ('status', models.CharField(choices=[('ordered', 'Ordered'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ordered', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordered_imaging', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='patients.patient')),
                ('technician', models.ForeignKey(blank=True, limit_choices_to={'role': 'lab'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_imaging', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imaging_orders', to='doctors.medicalrecord')),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medication_name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200)),
                ('dosage', models.CharField(help_text='e.g., 500mg', max_length=50)),
                ('frequency', models.CharField(help_text='e.g., 2x daily', max_length=100)),
                ('route', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenous'), ('im', 'Intramuscular'), ('subcutaneous', 'Subcutaneous'), ('topical', 'Topical'), ('inhalation', 'Inhalation'), ('rectal', 'Rectal'), ('other', 'Other')], default='oral', max_length=20)),
                ('duration', models.CharField(help_text='e.g., 7 days', max_length=50)),
                ('quantity', models.IntegerField(help_text='Total quantity to dispense')),
                ('refills', models.IntegerField(default=0, help_text='Number of refills allowed')),
                ('instructions', models.TextField(blank=True, help_text='Special instructions for patient')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('dispensed', 'Dispensed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('dispensed_at', models.DateTimeField(blank=True, null=True)),
                ('dispensed_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='doctors.medicalrecord')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='patients.patient')),
                ('pharmacist', models.ForeignKey(blank=True, limit_choices_to={'role': 'pharmacy'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
