# Generated by Django 6.0.6 on 2026-06-30 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagingorder',
            name='clarification_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='clarification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='clarification_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='clarification_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='imagingorder',
            name='needs_clarification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='laborder',
            name='clarification_request',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='clarification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='clarification_responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='clarification_response',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='laborder',
            name='needs_clarification',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked when waiting for lab/imaging results'),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='lock_reason',
            field=models.CharField(blank=True, help_text='Why is this record locked?', max_length=255),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='needs_nursing_care',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='nursing_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='nursing_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='nursing_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='workflow_status',
            field=models.CharField(choices=[('draft', 'Draft - Initial Assessment'), ('prescribed', 'Prescribed - Waiting for Pharmacy'), ('lab_ordered', 'Lab Tests Ordered - Waiting for Results'), ('imaging_ordered', 'Imaging Ordered - Waiting for Results'), ('lab_imaging_ordered', 'Lab & Imaging Ordered - Waiting for Results'), ('nursing_care', 'Nursing Care - Sent to Nurse'), ('completed', 'Completed - All Done'), ('cancelled', 'Cancelled')], default='draft', max_length=30),
        ),
        migrations.AlterField(
            model_name='imagingorder',
            name='clinical_indication',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='clinical_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='days_of_stay',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='differential_diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ml_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ml_medication_suggestions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ml_suggestion',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='ml_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptom_duration',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='symptom_severity',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment_plan',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='refills',
            field=models.IntegerField(default=0),
        ),
    ]
