# Generated by Django 6.0.6 on 2026-06-30 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_imagingorder_clarification_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagingorder',
            name='clinical_indication',
            field=models.TextField(help_text='Why this imaging is needed'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='clinical_notes',
            field=models.TextField(blank=True, help_text='What to look for'),
        ),
        migrations.AlterField(
            model_name='laborder',
            name='test_type',
            field=models.CharField(help_text='Blood, Urine, Stool, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.CharField(help_text='e.g., 500mg', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='duration',
            field=models.CharField(help_text='e.g., 7 days', max_length=50),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='frequency',
            field=models.CharField(help_text='e.g., 2x daily', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='instructions',
            field=models.TextField(blank=True, help_text='Special instructions for patient'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='quantity',
            field=models.IntegerField(help_text='Total quantity to dispense'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='refills',
            field=models.IntegerField(default=0, help_text='Number of refills allowed'),
        ),
    ]
